<?php

namespace SSitdikov\ATOL\Code;

interface ErrorCode
{

    const ERROR = 1;
    const ERROR_INCOMING_BAD_REQUEST = 2;
    const ERROR_INCOMING_OPERATION_NOT_SUPPORT = 3;
    const ERROR_INCOMING_MISSING_TOKEN = 4;
    const ERROR_INCOMING_NOT_EXIST_TOKEN = 5;
    const ERROR_INCOMING_EXPIRED_TOKEN = 6;
    const ERROR_INCOMING_QUEUE_TIMEOUT = 7;
    const ERROR_INCOMING_VALIDATION_EXCEPTION = 8;
    const ERROR_INCOMING_QUEUE_EXCEPTION = 9;
    const ERROR_INCOMING_EXIST_EXTERNAL_ID = 10;
    const ERROR_STATE_BAD_REQUEST = 11;
    const ERROR_STATE_MISSING_TOKEN = 12;
    const ERROR_STATE_NOT_EXIST_TOKEN = 13;
    const ERROR_STATE_EXPIRED_TOKEN = 14;
    const ERROR_STATE_MISSING_UUID = 15;
    const ERROR_STATE_NOT_FOUND = 16;
    const AUTH_BAD_REQUEST = 17;
    const AUTH_GEN_TOKEN = 18;
    const AUTH_WORKING_USER_OR_PASSWORD = 19;
    const ERROR_GROUP_CODE_TO_TOKEN = 22;
    const ERROR_IS_NULL_EXTERNAL_ID = 23;
}
